/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.angelobarbu.ui_bd;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.UIManager;

/**
 *
 * @author Angelo
 */
public class PassengersDelete extends javax.swing.JFrame {

    /**
     * Creates new form PassengersDelete
     */
    public PassengersDelete() {
        initComponents();
    }
    
    public boolean deletePassenger() {
        
        String passportNo = passengersDeleteText.getText();
        
        if (passportNo.equals(""))
            return false;
        
        try {
            
            String connectionUrl = "jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=zboruri_aeroport;";
            String username = "sa";
            String password = "herooftheworld";

            Connection con = DriverManager.getConnection(connectionUrl, username, password);

            String query = "DELETE FROM Pasageri WHERE NrPasaport = '" + passportNo + "'";
            PreparedStatement pSt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ResultSet rs = pSt.executeQuery();
            
            
            
        } catch(SQLException e) {
            e.printStackTrace();
            return false;
            
        }
        
       return true;
        
    }
    
    public boolean deletePassengerFlights() {
        
        String passportNo = passengersDeleteText.getText();
        
        if (passportNo.equals(""))
            return false;
        
        try {
            
            String connectionUrl = "jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=zboruri_aeroport;";
            String username = "sa";
            String password = "herooftheworld";

            Connection con = DriverManager.getConnection(connectionUrl, username, password);

            String query = "DELETE pz FROM PasageriZboruri pz INNER JOIN Pasageri p ON p.PasagerID = pz.PasagerID WHERE p.NrPasaport = '" + passportNo + "'";
            PreparedStatement pSt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ResultSet rs = pSt.executeQuery();
          
            
            
        } catch(SQLException e) {
            e.printStackTrace();
            return false;
        }
        
        return true;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passengersDeleteLabel = new javax.swing.JLabel();
        passengersDeleteText = new javax.swing.JTextField();
        passengersDeleteButton = new javax.swing.JButton();
        backToMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FLAssistant");

        passengersDeleteLabel.setText("Numarul pasaportului pasagerului ce va fi sters");

        passengersDeleteText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passengersDeleteTextKeyPressed(evt);
            }
        });

        passengersDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passengersDeleteButton.setText("Sterge");
        passengersDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengersDeleteButtonActionPerformed(evt);
            }
        });

        backToMenuButton.setText("< Inapoi la meniu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passengersDeleteLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(backToMenuButton)
                                .addGap(18, 18, 18)
                                .addComponent(passengersDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passengersDeleteText, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(passengersDeleteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passengersDeleteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengersDeleteButton)
                    .addComponent(backToMenuButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passengersDeleteTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passengersDeleteTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            passengersDeleteButton.requestFocus();
        }
    }//GEN-LAST:event_passengersDeleteTextKeyPressed

    private void passengersDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengersDeleteButtonActionPerformed
        if (deletePassengerFlights()) {
            if (deletePassenger()) {
                new DeleteSuccess().setVisible(true);
                passengersDeleteText.setText("");
            } else {
                new DeleteError().setVisible(true);
            }
        } else {
            new DeleteError().setVisible(true);
        }
    }//GEN-LAST:event_passengersDeleteButtonActionPerformed

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        dispose();
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch(Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengersDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JButton passengersDeleteButton;
    private javax.swing.JLabel passengersDeleteLabel;
    private javax.swing.JTextField passengersDeleteText;
    // End of variables declaration//GEN-END:variables
}
