/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.angelobarbu.ui_bd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelo
 */

public class PassengersDisplay extends javax.swing.JFrame {

    /**
     * Creates new form PassengersDisplay
     */
    
    public PassengersDisplay() {
        initComponents();
        showPassengers();
    }
    
    /*
    functie ce creeaza lista de pasageri prin conectarea bazei de date,
    trimiterea interogarii la baza de date si introducerea a fiecarei
    valori returnate de baza de date in lista de pasageri
    */
    public ArrayList<Passengers> getPassengersList() {
        
        ArrayList<Passengers> passengersList = new ArrayList<>();
        
        try {
            String connectionUrl = "jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=zboruri_aeroport;";
            String username = "sa";
            String password = "herooftheworld";
            Connection con = DriverManager.getConnection(connectionUrl, username, password);
            String flightNo = Home.flightNoText.getText();
            String selectQuery = "SELECT * FROM Pasageri " +
                                 "INNER JOIN (Zboruri INNER JOIN PasageriZboruri ON Zboruri.ZborID = PasageriZboruri.ZborID) ON Pasageri.PasagerID = PasageriZboruri.PasagerID " +
                                 "WHERE NrZbor = '" + flightNo + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(selectQuery);
            Passengers passenger;
            while (rs.next()) {
                passenger = new Passengers(rs.getInt("PasagerID"), rs.getString("Nume"), rs.getString("Prenume"), rs.getString("NrPasaport"),
                                        rs.getString("Adresa"), rs.getString("Oras"), rs.getString("Tara"), rs.getDate("DataNasterii"));
                passengersList.add(passenger);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return passengersList;
        
    }
    
    //introduce pasagerii din lista in JTable si ii afiseaza
    public void showPassengers() {
        
        ArrayList<Passengers> passengersList = getPassengersList();
        DefaultTableModel model = (DefaultTableModel) displayPassengers.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < passengersList.size(); i++) {
            row[0] = passengersList.get(i).getLastName();
            row[1] = passengersList.get(i).getFirstName();
            row[2] = passengersList.get(i).getPassportNo();
            row[3] = passengersList.get(i).getAddress();
            row[4] = passengersList.get(i).getCity();
            row[5] = passengersList.get(i).getCountry();
            row[6] = passengersList.get(i).getDateOfBirth();
            model.addRow(row);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        displayPassengers = new javax.swing.JTable();
        backToMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FLAssistant");

        displayPassengers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nume", "Prenume", "Nr Pasaport", "Adresa", "Oras", "Tara", "Data Nasterii"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayPassengers);

        backToMenuButton.setText("< Inapoi la meniu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToMenuButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToMenuButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        dispose();
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch(Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengersDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JTable displayPassengers;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
